# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('premon', models.CharField(max_length=120)),
                ('dateNaiss', models.DateField()),
                ('lieuNaiss', models.CharField(max_length=120)),
                ('login', models.CharField(max_length=120)),
                ('motdepass', models.CharField(max_length=120)),
            ],
        ),
    ]
